# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20170311_1541'),
    ]

    operations = [
    ]
